/**
 * build.js — embeds index.html into worker.js
 * Run: node build.js
 * Output: worker.js (ready to deploy with wrangler)
 */
import { readFileSync, writeFileSync } from 'fs';

const html = readFileSync('index.html', 'utf8');
const htmlJson = JSON.stringify(html); // safe: escapes backticks, ${, \

const worker = `/**
 * La Fournée — Cloudflare Worker
 * KV binding: LAFOURNEE_KV
 *
 * Routes:
 *   GET  /          — serve the game HTML
 *   POST /api/save  — save game state to KV (keyed by CF-Connecting-IP)
 *   GET  /api/load  — load game state from KV
 */

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

const MAX_PAYLOAD = 64 * 1024; // 64 KB

// Embedded game HTML (generated by build.js — do not edit manually)
const GAME_HTML = ${htmlJson};

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...CORS },
  });
}

function userKey(request) {
  const ip = request.headers.get('CF-Connecting-IP') || 'anonymous';
  return \`save:\${ip}\`;
}

async function handleSave(request, env) {
  const contentLength = parseInt(request.headers.get('Content-Length') || '0', 10);
  if (contentLength > MAX_PAYLOAD) return json({ error: 'Payload too large' }, 413);

  let body;
  try {
    body = await request.text();
    JSON.parse(body);
  } catch {
    return json({ error: 'Invalid JSON' }, 400);
  }

  const key = userKey(request);
  await env.LAFOURNEE_KV.put(key, body, { expirationTtl: 60 * 60 * 24 * 365 });
  return json({ ok: true });
}

async function handleLoad(request, env) {
  const key = userKey(request);
  const value = await env.LAFOURNEE_KV.get(key, 'text');
  if (!value) return json({ ok: false, error: 'No save found' }, 404);

  try {
    return json(JSON.parse(value));
  } catch {
    return json({ error: 'Corrupted save' }, 500);
  }
}

export default {
  async fetch(request, env) {
    const { method, pathname } = Object.assign(
      { method: request.method },
      { pathname: new URL(request.url).pathname }
    );

    if (method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });

    if (pathname === '/api/save' && method === 'POST') return handleSave(request, env);
    if (pathname === '/api/load' && method === 'GET')  return handleLoad(request, env);

    // Serve game for any other GET (/ or unknown paths)
    if (method === 'GET') {
      return new Response(GAME_HTML, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=60',
        },
      });
    }

    return new Response('Not Found', { status: 404 });
  },
};
`;

writeFileSync('worker.js', worker, 'utf8');
console.log(`worker.js written (${(worker.length / 1024).toFixed(1)} KB)`);
